#!/usr/bin/env bash
#a Bash script that displays Best School 10 timesi
#and say hi on the 9th iteration
i=0
until [ $i -eq 10 ];
do
	if [ $i == 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	((i++))
done
