#!/usr/bin/env bash
#a Bash script that displays Best School 10 timesi
#4 badluck, 8 is your chance
i=0
while [ $i -lt 10 ];
do
	if [ $i == 3 ]
	then
		echo "bad luck"
	elif [ $i == 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
