#!/usr/bin/env bash
# a Bash script that configures an Ubuntu server
if ! grep -q "facebook.com" /etc/hosts; then
	cp /etc/host ~/host.new
	echo "8.8.8.8	facebook.com" >> ~/hosts.new
	echo "127.0.0.2	localhost" >> ~/hosts.new
	cp -f ~/hosts.new /etc/hosts
fi
